//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AutonomousNavigationExampleEnvironmentStepRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AutonomousNavigationExampleEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg request_sent_timestamp;
        public AutonomousNavigationExampleAgentActionMsg action;

        public AutonomousNavigationExampleEnvironmentStepRequest()
        {
            this.request_sent_timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new AutonomousNavigationExampleAgentActionMsg();
        }

        public AutonomousNavigationExampleEnvironmentStepRequest(BuiltinInterfaces.TimeMsg request_sent_timestamp, AutonomousNavigationExampleAgentActionMsg action)
        {
            this.request_sent_timestamp = request_sent_timestamp;
            this.action = action;
        }

        public static AutonomousNavigationExampleEnvironmentStepRequest Deserialize(MessageDeserializer deserializer) => new AutonomousNavigationExampleEnvironmentStepRequest(deserializer);

        private AutonomousNavigationExampleEnvironmentStepRequest(MessageDeserializer deserializer)
        {
            this.request_sent_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = AutonomousNavigationExampleAgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_sent_timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "AutonomousNavigationExampleEnvironmentStepRequest: " +
            "\nrequest_sent_timestamp: " + request_sent_timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
