//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleEnvironmentStepRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg request_sent_timestamp;
        public ShootingExampleAgentActionMsg action;

        public ShootingExampleEnvironmentStepRequest()
        {
            this.request_sent_timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new ShootingExampleAgentActionMsg();
        }

        public ShootingExampleEnvironmentStepRequest(BuiltinInterfaces.TimeMsg request_sent_timestamp, ShootingExampleAgentActionMsg action)
        {
            this.request_sent_timestamp = request_sent_timestamp;
            this.action = action;
        }

        public static ShootingExampleEnvironmentStepRequest Deserialize(MessageDeserializer deserializer) => new ShootingExampleEnvironmentStepRequest(deserializer);

        private ShootingExampleEnvironmentStepRequest(MessageDeserializer deserializer)
        {
            this.request_sent_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = ShootingExampleAgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_sent_timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "ShootingExampleEnvironmentStepRequest: " +
            "\nrequest_sent_timestamp: " + request_sent_timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
