//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AutonomousNavigationExampleEnvironmentActionRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AutonomousNavigationExampleEnvironmentAction";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public AutonomousNavigationExampleAgentActionMsg action;

        public AutonomousNavigationExampleEnvironmentActionRequest()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new AutonomousNavigationExampleAgentActionMsg();
        }

        public AutonomousNavigationExampleEnvironmentActionRequest(BuiltinInterfaces.TimeMsg timestamp, AutonomousNavigationExampleAgentActionMsg action)
        {
            this.timestamp = timestamp;
            this.action = action;
        }

        public static AutonomousNavigationExampleEnvironmentActionRequest Deserialize(MessageDeserializer deserializer) => new AutonomousNavigationExampleEnvironmentActionRequest(deserializer);

        private AutonomousNavigationExampleEnvironmentActionRequest(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = AutonomousNavigationExampleAgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "AutonomousNavigationExampleEnvironmentActionRequest: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
