//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class EscoPilotExampleEnvironmentStepRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/EscoPilotExampleEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public EscoPilotExampleAgentActionMsg agent_action;
        public bool reset;

        public EscoPilotExampleEnvironmentStepRequest()
        {
            this.agent_action = new EscoPilotExampleAgentActionMsg();
            this.reset = false;
        }

        public EscoPilotExampleEnvironmentStepRequest(EscoPilotExampleAgentActionMsg agent_action, bool reset)
        {
            this.agent_action = agent_action;
            this.reset = reset;
        }

        public static EscoPilotExampleEnvironmentStepRequest Deserialize(MessageDeserializer deserializer) => new EscoPilotExampleEnvironmentStepRequest(deserializer);

        private EscoPilotExampleEnvironmentStepRequest(MessageDeserializer deserializer)
        {
            this.agent_action = EscoPilotExampleAgentActionMsg.Deserialize(deserializer);
            deserializer.Read(out this.reset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_action);
            serializer.Write(this.reset);
        }

        public override string ToString()
        {
            return "EscoPilotExampleEnvironmentStepRequest: " +
            "\nagent_action: " + agent_action.ToString() +
            "\nreset: " + reset.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
