//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class EscoPilotExampleEnvironmentStepResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/EscoPilotExampleEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public EscoPilotExampleAgentStateMsg agent_state;

        public EscoPilotExampleEnvironmentStepResponse()
        {
            this.agent_state = new EscoPilotExampleAgentStateMsg();
        }

        public EscoPilotExampleEnvironmentStepResponse(EscoPilotExampleAgentStateMsg agent_state)
        {
            this.agent_state = agent_state;
        }

        public static EscoPilotExampleEnvironmentStepResponse Deserialize(MessageDeserializer deserializer) => new EscoPilotExampleEnvironmentStepResponse(deserializer);

        private EscoPilotExampleEnvironmentStepResponse(MessageDeserializer deserializer)
        {
            this.agent_state = EscoPilotExampleAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_state);
        }

        public override string ToString()
        {
            return "EscoPilotExampleEnvironmentStepResponse: " +
            "\nagent_state: " + agent_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
