//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarSensorTestEnvironmentStateResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarSensorTestEnvironmentState";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public LidarSensorTestAgentStateMsg state;

        public LidarSensorTestEnvironmentStateResponse()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.state = new LidarSensorTestAgentStateMsg();
        }

        public LidarSensorTestEnvironmentStateResponse(BuiltinInterfaces.TimeMsg timestamp, LidarSensorTestAgentStateMsg state)
        {
            this.timestamp = timestamp;
            this.state = state;
        }

        public static LidarSensorTestEnvironmentStateResponse Deserialize(MessageDeserializer deserializer) => new LidarSensorTestEnvironmentStateResponse(deserializer);

        private LidarSensorTestEnvironmentStateResponse(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.state = LidarSensorTestAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "LidarSensorTestEnvironmentStateResponse: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
