//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarSensorTestEnvironmentStepResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarSensorTestEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public LidarSensorTestAgentStateMsg agent_state;

        public LidarSensorTestEnvironmentStepResponse()
        {
            this.agent_state = new LidarSensorTestAgentStateMsg();
        }

        public LidarSensorTestEnvironmentStepResponse(LidarSensorTestAgentStateMsg agent_state)
        {
            this.agent_state = agent_state;
        }

        public static LidarSensorTestEnvironmentStepResponse Deserialize(MessageDeserializer deserializer) => new LidarSensorTestEnvironmentStepResponse(deserializer);

        private LidarSensorTestEnvironmentStepResponse(MessageDeserializer deserializer)
        {
            this.agent_state = LidarSensorTestAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_state);
        }

        public override string ToString()
        {
            return "LidarSensorTestEnvironmentStepResponse: " +
            "\nagent_state: " + agent_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
