//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarTestEnvironmentStepResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarTestEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public LidarTestAgentStateMsg agent_state;

        public LidarTestEnvironmentStepResponse()
        {
            this.agent_state = new LidarTestAgentStateMsg();
        }

        public LidarTestEnvironmentStepResponse(LidarTestAgentStateMsg agent_state)
        {
            this.agent_state = agent_state;
        }

        public static LidarTestEnvironmentStepResponse Deserialize(MessageDeserializer deserializer) => new LidarTestEnvironmentStepResponse(deserializer);

        private LidarTestEnvironmentStepResponse(MessageDeserializer deserializer)
        {
            this.agent_state = LidarTestAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_state);
        }

        public override string ToString()
        {
            return "LidarTestEnvironmentStepResponse: " +
            "\nagent_state: " + agent_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
