//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarSensorTestEnvironmentActionRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarSensorTestEnvironmentAction";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public LidarSensorTestAgentActionMsg action;

        public LidarSensorTestEnvironmentActionRequest()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new LidarSensorTestAgentActionMsg();
        }

        public LidarSensorTestEnvironmentActionRequest(BuiltinInterfaces.TimeMsg timestamp, LidarSensorTestAgentActionMsg action)
        {
            this.timestamp = timestamp;
            this.action = action;
        }

        public static LidarSensorTestEnvironmentActionRequest Deserialize(MessageDeserializer deserializer) => new LidarSensorTestEnvironmentActionRequest(deserializer);

        private LidarSensorTestEnvironmentActionRequest(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = LidarSensorTestAgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "LidarSensorTestEnvironmentActionRequest: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
