//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarSensorTestEnvironmentStepRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarSensorTestEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public LidarSensorTestAgentActionMsg agent_action;
        public bool reset;

        public LidarSensorTestEnvironmentStepRequest()
        {
            this.agent_action = new LidarSensorTestAgentActionMsg();
            this.reset = false;
        }

        public LidarSensorTestEnvironmentStepRequest(LidarSensorTestAgentActionMsg agent_action, bool reset)
        {
            this.agent_action = agent_action;
            this.reset = reset;
        }

        public static LidarSensorTestEnvironmentStepRequest Deserialize(MessageDeserializer deserializer) => new LidarSensorTestEnvironmentStepRequest(deserializer);

        private LidarSensorTestEnvironmentStepRequest(MessageDeserializer deserializer)
        {
            this.agent_action = LidarSensorTestAgentActionMsg.Deserialize(deserializer);
            deserializer.Read(out this.reset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_action);
            serializer.Write(this.reset);
        }

        public override string ToString()
        {
            return "LidarSensorTestEnvironmentStepRequest: " +
            "\nagent_action: " + agent_action.ToString() +
            "\nreset: " + reset.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
