//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class PoseSensorAndActuatorTestEnvironmentStateResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/PoseSensorAndActuatorTestEnvironmentState";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public PoseSensorAndActuatorTestAgentStateMsg state;

        public PoseSensorAndActuatorTestEnvironmentStateResponse()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.state = new PoseSensorAndActuatorTestAgentStateMsg();
        }

        public PoseSensorAndActuatorTestEnvironmentStateResponse(BuiltinInterfaces.TimeMsg timestamp, PoseSensorAndActuatorTestAgentStateMsg state)
        {
            this.timestamp = timestamp;
            this.state = state;
        }

        public static PoseSensorAndActuatorTestEnvironmentStateResponse Deserialize(MessageDeserializer deserializer) => new PoseSensorAndActuatorTestEnvironmentStateResponse(deserializer);

        private PoseSensorAndActuatorTestEnvironmentStateResponse(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.state = PoseSensorAndActuatorTestAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "PoseSensorAndActuatorTestEnvironmentStateResponse: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
