//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class PoseSensorAndActuatorTestEnvironmentStepResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/PoseSensorAndActuatorTestEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public PoseSensorAndActuatorTestAgentStateMsg agent_state;

        public PoseSensorAndActuatorTestEnvironmentStepResponse()
        {
            this.agent_state = new PoseSensorAndActuatorTestAgentStateMsg();
        }

        public PoseSensorAndActuatorTestEnvironmentStepResponse(PoseSensorAndActuatorTestAgentStateMsg agent_state)
        {
            this.agent_state = agent_state;
        }

        public static PoseSensorAndActuatorTestEnvironmentStepResponse Deserialize(MessageDeserializer deserializer) => new PoseSensorAndActuatorTestEnvironmentStepResponse(deserializer);

        private PoseSensorAndActuatorTestEnvironmentStepResponse(MessageDeserializer deserializer)
        {
            this.agent_state = PoseSensorAndActuatorTestAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_state);
        }

        public override string ToString()
        {
            return "PoseSensorAndActuatorTestEnvironmentStepResponse: " +
            "\nagent_state: " + agent_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
