//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class PoseSensorAndActuatorTestEnvironmentActionRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/PoseSensorAndActuatorTestEnvironmentAction";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public PoseSensorAndActuatorTestAgentActionMsg action;

        public PoseSensorAndActuatorTestEnvironmentActionRequest()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new PoseSensorAndActuatorTestAgentActionMsg();
        }

        public PoseSensorAndActuatorTestEnvironmentActionRequest(BuiltinInterfaces.TimeMsg timestamp, PoseSensorAndActuatorTestAgentActionMsg action)
        {
            this.timestamp = timestamp;
            this.action = action;
        }

        public static PoseSensorAndActuatorTestEnvironmentActionRequest Deserialize(MessageDeserializer deserializer) => new PoseSensorAndActuatorTestEnvironmentActionRequest(deserializer);

        private PoseSensorAndActuatorTestEnvironmentActionRequest(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = PoseSensorAndActuatorTestAgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "PoseSensorAndActuatorTestEnvironmentActionRequest: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
