//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleEnvironmentResetRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleEnvironmentReset";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg request_sent_timestamp;
        public ShootingExampleAgentResetMsg reset_action;

        public ShootingExampleEnvironmentResetRequest()
        {
            this.request_sent_timestamp = new BuiltinInterfaces.TimeMsg();
            this.reset_action = new ShootingExampleAgentResetMsg();
        }

        public ShootingExampleEnvironmentResetRequest(BuiltinInterfaces.TimeMsg request_sent_timestamp, ShootingExampleAgentResetMsg reset_action)
        {
            this.request_sent_timestamp = request_sent_timestamp;
            this.reset_action = reset_action;
        }

        public static ShootingExampleEnvironmentResetRequest Deserialize(MessageDeserializer deserializer) => new ShootingExampleEnvironmentResetRequest(deserializer);

        private ShootingExampleEnvironmentResetRequest(MessageDeserializer deserializer)
        {
            this.request_sent_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.reset_action = ShootingExampleAgentResetMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_sent_timestamp);
            serializer.Write(this.reset_action);
        }

        public override string ToString()
        {
            return "ShootingExampleEnvironmentResetRequest: " +
            "\nrequest_sent_timestamp: " + request_sent_timestamp.ToString() +
            "\nreset_action: " + reset_action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
