//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TriggerSensorTestEnvironmentActionRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TriggerSensorTestEnvironmentAction";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public TriggerSensorTestAgentActionMsg action;

        public TriggerSensorTestEnvironmentActionRequest()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new TriggerSensorTestAgentActionMsg();
        }

        public TriggerSensorTestEnvironmentActionRequest(BuiltinInterfaces.TimeMsg timestamp, TriggerSensorTestAgentActionMsg action)
        {
            this.timestamp = timestamp;
            this.action = action;
        }

        public static TriggerSensorTestEnvironmentActionRequest Deserialize(MessageDeserializer deserializer) => new TriggerSensorTestEnvironmentActionRequest(deserializer);

        private TriggerSensorTestEnvironmentActionRequest(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = TriggerSensorTestAgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "TriggerSensorTestEnvironmentActionRequest: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
