//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TriggerSensorTestEnvironmentStepResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TriggerSensorTestEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public TriggerSensorTestAgentStateMsg agent_state;

        public TriggerSensorTestEnvironmentStepResponse()
        {
            this.agent_state = new TriggerSensorTestAgentStateMsg();
        }

        public TriggerSensorTestEnvironmentStepResponse(TriggerSensorTestAgentStateMsg agent_state)
        {
            this.agent_state = agent_state;
        }

        public static TriggerSensorTestEnvironmentStepResponse Deserialize(MessageDeserializer deserializer) => new TriggerSensorTestEnvironmentStepResponse(deserializer);

        private TriggerSensorTestEnvironmentStepResponse(MessageDeserializer deserializer)
        {
            this.agent_state = TriggerSensorTestAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_state);
        }

        public override string ToString()
        {
            return "TriggerSensorTestEnvironmentStepResponse: " +
            "\nagent_state: " + agent_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
