//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TriggerSensorTestEnvironmentResetResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TriggerSensorTestEnvironmentReset";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;

        public TriggerSensorTestEnvironmentResetResponse()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
        }

        public TriggerSensorTestEnvironmentResetResponse(BuiltinInterfaces.TimeMsg timestamp)
        {
            this.timestamp = timestamp;
        }

        public static TriggerSensorTestEnvironmentResetResponse Deserialize(MessageDeserializer deserializer) => new TriggerSensorTestEnvironmentResetResponse(deserializer);

        private TriggerSensorTestEnvironmentResetResponse(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
        }

        public override string ToString()
        {
            return "TriggerSensorTestEnvironmentResetResponse: " +
            "\ntimestamp: " + timestamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
