//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TwistSensorAndActuatorTestEnvironmentActionRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TwistSensorAndActuatorTestEnvironmentAction";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public TwistSensorAndActuatorTestAgentActionMsg action;

        public TwistSensorAndActuatorTestEnvironmentActionRequest()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new TwistSensorAndActuatorTestAgentActionMsg();
        }

        public TwistSensorAndActuatorTestEnvironmentActionRequest(BuiltinInterfaces.TimeMsg timestamp, TwistSensorAndActuatorTestAgentActionMsg action)
        {
            this.timestamp = timestamp;
            this.action = action;
        }

        public static TwistSensorAndActuatorTestEnvironmentActionRequest Deserialize(MessageDeserializer deserializer) => new TwistSensorAndActuatorTestEnvironmentActionRequest(deserializer);

        private TwistSensorAndActuatorTestEnvironmentActionRequest(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = TwistSensorAndActuatorTestAgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "TwistSensorAndActuatorTestEnvironmentActionRequest: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
