//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TwistSensorAndActuatorTestEnvironmentStateResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TwistSensorAndActuatorTestEnvironmentState";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        public TwistSensorAndActuatorTestAgentStateMsg state;

        public TwistSensorAndActuatorTestEnvironmentStateResponse()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.state = new TwistSensorAndActuatorTestAgentStateMsg();
        }

        public TwistSensorAndActuatorTestEnvironmentStateResponse(BuiltinInterfaces.TimeMsg timestamp, TwistSensorAndActuatorTestAgentStateMsg state)
        {
            this.timestamp = timestamp;
            this.state = state;
        }

        public static TwistSensorAndActuatorTestEnvironmentStateResponse Deserialize(MessageDeserializer deserializer) => new TwistSensorAndActuatorTestEnvironmentStateResponse(deserializer);

        private TwistSensorAndActuatorTestEnvironmentStateResponse(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.state = TwistSensorAndActuatorTestAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "TwistSensorAndActuatorTestEnvironmentStateResponse: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
