//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC2EnvironmentStepRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC2EnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg request_sent_timestamp;
        public UC2AgentActionMsg action;

        public UC2EnvironmentStepRequest()
        {
            this.request_sent_timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new UC2AgentActionMsg();
        }

        public UC2EnvironmentStepRequest(BuiltinInterfaces.TimeMsg request_sent_timestamp, UC2AgentActionMsg action)
        {
            this.request_sent_timestamp = request_sent_timestamp;
            this.action = action;
        }

        public static UC2EnvironmentStepRequest Deserialize(MessageDeserializer deserializer) => new UC2EnvironmentStepRequest(deserializer);

        private UC2EnvironmentStepRequest(MessageDeserializer deserializer)
        {
            this.request_sent_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = UC2AgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_sent_timestamp);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "UC2EnvironmentStepRequest: " +
            "\nrequest_sent_timestamp: " + request_sent_timestamp.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
