//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TankActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TankAction";
        public override string RosMessageName => k_RosMessageName;

        public Twist2DMsg target_twist;
        public Turret2DActuatorMsg turret_actuator;

        public TankActionMsg()
        {
            this.target_twist = new Twist2DMsg();
            this.turret_actuator = new Turret2DActuatorMsg();
        }

        public TankActionMsg(Twist2DMsg target_twist, Turret2DActuatorMsg turret_actuator)
        {
            this.target_twist = target_twist;
            this.turret_actuator = turret_actuator;
        }

        public static TankActionMsg Deserialize(MessageDeserializer deserializer) => new TankActionMsg(deserializer);

        private TankActionMsg(MessageDeserializer deserializer)
        {
            this.target_twist = Twist2DMsg.Deserialize(deserializer);
            this.turret_actuator = Turret2DActuatorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_twist);
            serializer.Write(this.turret_actuator);
        }

        public override string ToString()
        {
            return "TankActionMsg: " +
            "\ntarget_twist: " + target_twist.ToString() +
            "\nturret_actuator: " + turret_actuator.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
