//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TankStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TankState";
        public override string RosMessageName => k_RosMessageName;

        public Pose2DMsg pose;
        public Twist2DMsg twist;
        public HealthInfoMsg health_info;
        public SmartLaserScanMsg smart_laser_scan;
        public Turret2DSensorMsg turret_sensor;

        public TankStateMsg()
        {
            this.pose = new Pose2DMsg();
            this.twist = new Twist2DMsg();
            this.health_info = new HealthInfoMsg();
            this.smart_laser_scan = new SmartLaserScanMsg();
            this.turret_sensor = new Turret2DSensorMsg();
        }

        public TankStateMsg(Pose2DMsg pose, Twist2DMsg twist, HealthInfoMsg health_info, SmartLaserScanMsg smart_laser_scan, Turret2DSensorMsg turret_sensor)
        {
            this.pose = pose;
            this.twist = twist;
            this.health_info = health_info;
            this.smart_laser_scan = smart_laser_scan;
            this.turret_sensor = turret_sensor;
        }

        public static TankStateMsg Deserialize(MessageDeserializer deserializer) => new TankStateMsg(deserializer);

        private TankStateMsg(MessageDeserializer deserializer)
        {
            this.pose = Pose2DMsg.Deserialize(deserializer);
            this.twist = Twist2DMsg.Deserialize(deserializer);
            this.health_info = HealthInfoMsg.Deserialize(deserializer);
            this.smart_laser_scan = SmartLaserScanMsg.Deserialize(deserializer);
            this.turret_sensor = Turret2DSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.twist);
            serializer.Write(this.health_info);
            serializer.Write(this.smart_laser_scan);
            serializer.Write(this.turret_sensor);
        }

        public override string ToString()
        {
            return "TankStateMsg: " +
            "\npose: " + pose.ToString() +
            "\ntwist: " + twist.ToString() +
            "\nhealth_info: " + health_info.ToString() +
            "\nsmart_laser_scan: " + smart_laser_scan.ToString() +
            "\nturret_sensor: " + turret_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
