//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class Twist2DMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/Twist2D";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float theta;

        public Twist2DMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.theta = 0.0f;
        }

        public Twist2DMsg(float x, float y, float theta)
        {
            this.x = x;
            this.y = y;
            this.theta = theta;
        }

        public static Twist2DMsg Deserialize(MessageDeserializer deserializer) => new Twist2DMsg(deserializer);

        private Twist2DMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.theta);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.theta);
        }

        public override string ToString()
        {
            return "Twist2DMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\ntheta: " + theta.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
