//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC1AgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC1AgentAction";
        public override string RosMessageName => k_RosMessageName;

        public TankActionMsg tank;

        public UC1AgentActionMsg()
        {
            this.tank = new TankActionMsg();
        }

        public UC1AgentActionMsg(TankActionMsg tank)
        {
            this.tank = tank;
        }

        public static UC1AgentActionMsg Deserialize(MessageDeserializer deserializer) => new UC1AgentActionMsg(deserializer);

        private UC1AgentActionMsg(MessageDeserializer deserializer)
        {
            this.tank = TankActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank);
        }

        public override string ToString()
        {
            return "UC1AgentActionMsg: " +
            "\ntank: " + tank.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
