//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC1AgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC1AgentState";
        public override string RosMessageName => k_RosMessageName;

        public TankStateMsg tank;
        public Pose2DMsg target_pose;
        public TriggerSensorMsg target_trigger_sensor;

        public UC1AgentStateMsg()
        {
            this.tank = new TankStateMsg();
            this.target_pose = new Pose2DMsg();
            this.target_trigger_sensor = new TriggerSensorMsg();
        }

        public UC1AgentStateMsg(TankStateMsg tank, Pose2DMsg target_pose, TriggerSensorMsg target_trigger_sensor)
        {
            this.tank = tank;
            this.target_pose = target_pose;
            this.target_trigger_sensor = target_trigger_sensor;
        }

        public static UC1AgentStateMsg Deserialize(MessageDeserializer deserializer) => new UC1AgentStateMsg(deserializer);

        private UC1AgentStateMsg(MessageDeserializer deserializer)
        {
            this.tank = TankStateMsg.Deserialize(deserializer);
            this.target_pose = Pose2DMsg.Deserialize(deserializer);
            this.target_trigger_sensor = TriggerSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank);
            serializer.Write(this.target_pose);
            serializer.Write(this.target_trigger_sensor);
        }

        public override string ToString()
        {
            return "UC1AgentStateMsg: " +
            "\ntank: " + tank.ToString() +
            "\ntarget_pose: " + target_pose.ToString() +
            "\ntarget_trigger_sensor: " + target_trigger_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
