//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC2AgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC2AgentState";
        public override string RosMessageName => k_RosMessageName;

        public TankStateMsg tank;
        public Pose2DMsg target_pose;
        public HealthInfoMsg target_health_info;

        public UC2AgentStateMsg()
        {
            this.tank = new TankStateMsg();
            this.target_pose = new Pose2DMsg();
            this.target_health_info = new HealthInfoMsg();
        }

        public UC2AgentStateMsg(TankStateMsg tank, Pose2DMsg target_pose, HealthInfoMsg target_health_info)
        {
            this.tank = tank;
            this.target_pose = target_pose;
            this.target_health_info = target_health_info;
        }

        public static UC2AgentStateMsg Deserialize(MessageDeserializer deserializer) => new UC2AgentStateMsg(deserializer);

        private UC2AgentStateMsg(MessageDeserializer deserializer)
        {
            this.tank = TankStateMsg.Deserialize(deserializer);
            this.target_pose = Pose2DMsg.Deserialize(deserializer);
            this.target_health_info = HealthInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank);
            serializer.Write(this.target_pose);
            serializer.Write(this.target_health_info);
        }

        public override string ToString()
        {
            return "UC2AgentStateMsg: " +
            "\ntank: " + tank.ToString() +
            "\ntarget_pose: " + target_pose.ToString() +
            "\ntarget_health_info: " + target_health_info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
