//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AutonomousNavigationExampleEnvironmentStepResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AutonomousNavigationExampleEnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public AutonomousNavigationExampleAgentStateMsg agent_state;

        public AutonomousNavigationExampleEnvironmentStepResponse()
        {
            this.agent_state = new AutonomousNavigationExampleAgentStateMsg();
        }

        public AutonomousNavigationExampleEnvironmentStepResponse(AutonomousNavigationExampleAgentStateMsg agent_state)
        {
            this.agent_state = agent_state;
        }

        public static AutonomousNavigationExampleEnvironmentStepResponse Deserialize(MessageDeserializer deserializer) => new AutonomousNavigationExampleEnvironmentStepResponse(deserializer);

        private AutonomousNavigationExampleEnvironmentStepResponse(MessageDeserializer deserializer)
        {
            this.agent_state = AutonomousNavigationExampleAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_state);
        }

        public override string ToString()
        {
            return "AutonomousNavigationExampleEnvironmentStepResponse: " +
            "\nagent_state: " + agent_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
