builtin_interfaces/Time request_sent_timestamp
AutonomousNavigationExampleAgentReset reset_action
---
builtin_interfaces/Time request_received_timestamp
builtin_interfaces/Time response_sent_timestamp
builtin_interfaces/Time response_received_timestamp
AutonomousNavigationExampleAgentState state