//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class EnemySensorMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/EnemySensor";
        public override string RosMessageName => k_RosMessageName;

        public float health;

        public EnemySensorMsg()
        {
            this.health = 0.0f;
        }

        public EnemySensorMsg(float health)
        {
            this.health = health;
        }

        public static EnemySensorMsg Deserialize(MessageDeserializer deserializer) => new EnemySensorMsg(deserializer);

        private EnemySensorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.health);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.health);
        }

        public override string ToString()
        {
            return "EnemySensorMsg: " +
            "\nhealth: " + health.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
