//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AutonomousNavigationExampleAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AutonomousNavigationExampleAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose_sensor;
        public Geometry.TwistMsg twist_sensor;
        public Sensor.LaserScanMsg lidar_sensor;
        public HealthSensorMsg health_sensor;
        public Geometry.PoseMsg target_pose_sensor;
        public TriggerSensorMsg target_trigger_sensor;

        public AutonomousNavigationExampleAgentStateMsg()
        {
            this.pose_sensor = new Geometry.PoseMsg();
            this.twist_sensor = new Geometry.TwistMsg();
            this.lidar_sensor = new Sensor.LaserScanMsg();
            this.health_sensor = new HealthSensorMsg();
            this.target_pose_sensor = new Geometry.PoseMsg();
            this.target_trigger_sensor = new TriggerSensorMsg();
        }

        public AutonomousNavigationExampleAgentStateMsg(Geometry.PoseMsg pose_sensor, Geometry.TwistMsg twist_sensor, Sensor.LaserScanMsg lidar_sensor, HealthSensorMsg health_sensor, Geometry.PoseMsg target_pose_sensor, TriggerSensorMsg target_trigger_sensor)
        {
            this.pose_sensor = pose_sensor;
            this.twist_sensor = twist_sensor;
            this.lidar_sensor = lidar_sensor;
            this.health_sensor = health_sensor;
            this.target_pose_sensor = target_pose_sensor;
            this.target_trigger_sensor = target_trigger_sensor;
        }

        public static AutonomousNavigationExampleAgentStateMsg Deserialize(MessageDeserializer deserializer) => new AutonomousNavigationExampleAgentStateMsg(deserializer);

        private AutonomousNavigationExampleAgentStateMsg(MessageDeserializer deserializer)
        {
            this.pose_sensor = Geometry.PoseMsg.Deserialize(deserializer);
            this.twist_sensor = Geometry.TwistMsg.Deserialize(deserializer);
            this.lidar_sensor = Sensor.LaserScanMsg.Deserialize(deserializer);
            this.health_sensor = HealthSensorMsg.Deserialize(deserializer);
            this.target_pose_sensor = Geometry.PoseMsg.Deserialize(deserializer);
            this.target_trigger_sensor = TriggerSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_sensor);
            serializer.Write(this.twist_sensor);
            serializer.Write(this.lidar_sensor);
            serializer.Write(this.health_sensor);
            serializer.Write(this.target_pose_sensor);
            serializer.Write(this.target_trigger_sensor);
        }

        public override string ToString()
        {
            return "AutonomousNavigationExampleAgentStateMsg: " +
            "\npose_sensor: " + pose_sensor.ToString() +
            "\ntwist_sensor: " + twist_sensor.ToString() +
            "\nlidar_sensor: " + lidar_sensor.ToString() +
            "\nhealth_sensor: " + health_sensor.ToString() +
            "\ntarget_pose_sensor: " + target_pose_sensor.ToString() +
            "\ntarget_trigger_sensor: " + target_trigger_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
