//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AutonomousNavigationExampleAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AutonomousNavigationExampleAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg twist;

        public AutonomousNavigationExampleAgentActionMsg()
        {
            this.twist = new Geometry.TwistMsg();
        }

        public AutonomousNavigationExampleAgentActionMsg(Geometry.TwistMsg twist)
        {
            this.twist = twist;
        }

        public static AutonomousNavigationExampleAgentActionMsg Deserialize(MessageDeserializer deserializer) => new AutonomousNavigationExampleAgentActionMsg(deserializer);

        private AutonomousNavigationExampleAgentActionMsg(MessageDeserializer deserializer)
        {
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "AutonomousNavigationExampleAgentActionMsg: " +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
