//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class HealthSensorMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/HealthSensor";
        public override string RosMessageName => k_RosMessageName;

        public float max_health;
        public float health;

        public HealthSensorMsg()
        {
            this.max_health = 0.0f;
            this.health = 0.0f;
        }

        public HealthSensorMsg(float max_health, float health)
        {
            this.max_health = max_health;
            this.health = health;
        }

        public static HealthSensorMsg Deserialize(MessageDeserializer deserializer) => new HealthSensorMsg(deserializer);

        private HealthSensorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.max_health);
            deserializer.Read(out this.health);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.max_health);
            serializer.Write(this.health);
        }

        public override string ToString()
        {
            return "HealthSensorMsg: " +
            "\nmax_health: " + max_health.ToString() +
            "\nhealth: " + health.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
