//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose_sensor;
        public Geometry.TwistMsg twist_sensor;
        public SmartLidarSensorMsg smart_lidar_sensor;
        public HealthSensorMsg health_sensor;
        public Turret2DSensorMsg turret_sensor;

        public ShootingExampleAgentStateMsg()
        {
            this.pose_sensor = new Geometry.PoseMsg();
            this.twist_sensor = new Geometry.TwistMsg();
            this.smart_lidar_sensor = new SmartLidarSensorMsg();
            this.health_sensor = new HealthSensorMsg();
            this.turret_sensor = new Turret2DSensorMsg();
        }

        public ShootingExampleAgentStateMsg(Geometry.PoseMsg pose_sensor, Geometry.TwistMsg twist_sensor, SmartLidarSensorMsg smart_lidar_sensor, HealthSensorMsg health_sensor, Turret2DSensorMsg turret_sensor)
        {
            this.pose_sensor = pose_sensor;
            this.twist_sensor = twist_sensor;
            this.smart_lidar_sensor = smart_lidar_sensor;
            this.health_sensor = health_sensor;
            this.turret_sensor = turret_sensor;
        }

        public static ShootingExampleAgentStateMsg Deserialize(MessageDeserializer deserializer) => new ShootingExampleAgentStateMsg(deserializer);

        private ShootingExampleAgentStateMsg(MessageDeserializer deserializer)
        {
            this.pose_sensor = Geometry.PoseMsg.Deserialize(deserializer);
            this.twist_sensor = Geometry.TwistMsg.Deserialize(deserializer);
            this.smart_lidar_sensor = SmartLidarSensorMsg.Deserialize(deserializer);
            this.health_sensor = HealthSensorMsg.Deserialize(deserializer);
            this.turret_sensor = Turret2DSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_sensor);
            serializer.Write(this.twist_sensor);
            serializer.Write(this.smart_lidar_sensor);
            serializer.Write(this.health_sensor);
            serializer.Write(this.turret_sensor);
        }

        public override string ToString()
        {
            return "ShootingExampleAgentStateMsg: " +
            "\npose_sensor: " + pose_sensor.ToString() +
            "\ntwist_sensor: " + twist_sensor.ToString() +
            "\nsmart_lidar_sensor: " + smart_lidar_sensor.ToString() +
            "\nhealth_sensor: " + health_sensor.ToString() +
            "\nturret_sensor: " + turret_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
