//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg twist_actuator;
        public Turret2DActuatorMsg turret_actuator;

        public ShootingExampleAgentActionMsg()
        {
            this.twist_actuator = new Geometry.TwistMsg();
            this.turret_actuator = new Turret2DActuatorMsg();
        }

        public ShootingExampleAgentActionMsg(Geometry.TwistMsg twist_actuator, Turret2DActuatorMsg turret_actuator)
        {
            this.twist_actuator = twist_actuator;
            this.turret_actuator = turret_actuator;
        }

        public static ShootingExampleAgentActionMsg Deserialize(MessageDeserializer deserializer) => new ShootingExampleAgentActionMsg(deserializer);

        private ShootingExampleAgentActionMsg(MessageDeserializer deserializer)
        {
            this.twist_actuator = Geometry.TwistMsg.Deserialize(deserializer);
            this.turret_actuator = Turret2DActuatorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist_actuator);
            serializer.Write(this.turret_actuator);
        }

        public override string ToString()
        {
            return "ShootingExampleAgentActionMsg: " +
            "\ntwist_actuator: " + twist_actuator.ToString() +
            "\nturret_actuator: " + turret_actuator.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
