//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AutonomousNavigationExampleAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AutonomousNavigationExampleAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg twist;
        public Geometry.PoseMsg agent_target_pose;
        public Geometry.PoseMsg target_target_pose;

        public AutonomousNavigationExampleAgentActionMsg()
        {
            this.twist = new Geometry.TwistMsg();
            this.agent_target_pose = new Geometry.PoseMsg();
            this.target_target_pose = new Geometry.PoseMsg();
        }

        public AutonomousNavigationExampleAgentActionMsg(Geometry.TwistMsg twist, Geometry.PoseMsg agent_target_pose, Geometry.PoseMsg target_target_pose)
        {
            this.twist = twist;
            this.agent_target_pose = agent_target_pose;
            this.target_target_pose = target_target_pose;
        }

        public static AutonomousNavigationExampleAgentActionMsg Deserialize(MessageDeserializer deserializer) => new AutonomousNavigationExampleAgentActionMsg(deserializer);

        private AutonomousNavigationExampleAgentActionMsg(MessageDeserializer deserializer)
        {
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
            this.agent_target_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.target_target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist);
            serializer.Write(this.agent_target_pose);
            serializer.Write(this.target_target_pose);
        }

        public override string ToString()
        {
            return "AutonomousNavigationExampleAgentActionMsg: " +
            "\ntwist: " + twist.ToString() +
            "\nagent_target_pose: " + agent_target_pose.ToString() +
            "\ntarget_target_pose: " + target_target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
