//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleEnvironmentResetResponse : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleEnvironmentReset";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg request_received_timestamp;
        public BuiltinInterfaces.TimeMsg response_sent_timestamp;
        public BuiltinInterfaces.TimeMsg response_received_timestamp;
        public ShootingExampleAgentStateMsg state;

        public ShootingExampleEnvironmentResetResponse()
        {
            this.request_received_timestamp = new BuiltinInterfaces.TimeMsg();
            this.response_sent_timestamp = new BuiltinInterfaces.TimeMsg();
            this.response_received_timestamp = new BuiltinInterfaces.TimeMsg();
            this.state = new ShootingExampleAgentStateMsg();
        }

        public ShootingExampleEnvironmentResetResponse(BuiltinInterfaces.TimeMsg request_received_timestamp, BuiltinInterfaces.TimeMsg response_sent_timestamp, BuiltinInterfaces.TimeMsg response_received_timestamp, ShootingExampleAgentStateMsg state)
        {
            this.request_received_timestamp = request_received_timestamp;
            this.response_sent_timestamp = response_sent_timestamp;
            this.response_received_timestamp = response_received_timestamp;
            this.state = state;
        }

        public static ShootingExampleEnvironmentResetResponse Deserialize(MessageDeserializer deserializer) => new ShootingExampleEnvironmentResetResponse(deserializer);

        private ShootingExampleEnvironmentResetResponse(MessageDeserializer deserializer)
        {
            this.request_received_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.response_sent_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.response_received_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.state = ShootingExampleAgentStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_received_timestamp);
            serializer.Write(this.response_sent_timestamp);
            serializer.Write(this.response_received_timestamp);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ShootingExampleEnvironmentResetResponse: " +
            "\nrequest_received_timestamp: " + request_received_timestamp.ToString() +
            "\nresponse_sent_timestamp: " + response_sent_timestamp.ToString() +
            "\nresponse_received_timestamp: " + response_received_timestamp.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
