//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AgentAction";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg target_position;

        public AgentActionMsg()
        {
            this.target_position = new Geometry.Vector3Msg();
        }

        public AgentActionMsg(Geometry.Vector3Msg target_position)
        {
            this.target_position = target_position;
        }

        public static AgentActionMsg Deserialize(MessageDeserializer deserializer) => new AgentActionMsg(deserializer);

        private AgentActionMsg(MessageDeserializer deserializer)
        {
            this.target_position = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_position);
        }

        public override string ToString()
        {
            return "AgentActionMsg: " +
            "\ntarget_position: " + target_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
