//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class AutonomousNavigationExampleAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/AutonomousNavigationExampleAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;
        public Geometry.TwistMsg twist;
        public Geometry.PoseMsg target_pose;
        //  sensor_msgs/LaserScan laser_scan
        public SmartLidarSensorMsg smart_lidar_sensor;
        public TriggerSensorMsg collision_trigger_sensor;
        public TriggerSensorMsg target_trigger_sensor;

        public AutonomousNavigationExampleAgentStateMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.twist = new Geometry.TwistMsg();
            this.target_pose = new Geometry.PoseMsg();
            this.smart_lidar_sensor = new SmartLidarSensorMsg();
            this.collision_trigger_sensor = new TriggerSensorMsg();
            this.target_trigger_sensor = new TriggerSensorMsg();
        }

        public AutonomousNavigationExampleAgentStateMsg(Geometry.PoseMsg pose, Geometry.TwistMsg twist, Geometry.PoseMsg target_pose, SmartLidarSensorMsg smart_lidar_sensor, TriggerSensorMsg collision_trigger_sensor, TriggerSensorMsg target_trigger_sensor)
        {
            this.pose = pose;
            this.twist = twist;
            this.target_pose = target_pose;
            this.smart_lidar_sensor = smart_lidar_sensor;
            this.collision_trigger_sensor = collision_trigger_sensor;
            this.target_trigger_sensor = target_trigger_sensor;
        }

        public static AutonomousNavigationExampleAgentStateMsg Deserialize(MessageDeserializer deserializer) => new AutonomousNavigationExampleAgentStateMsg(deserializer);

        private AutonomousNavigationExampleAgentStateMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.smart_lidar_sensor = SmartLidarSensorMsg.Deserialize(deserializer);
            this.collision_trigger_sensor = TriggerSensorMsg.Deserialize(deserializer);
            this.target_trigger_sensor = TriggerSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.twist);
            serializer.Write(this.target_pose);
            serializer.Write(this.smart_lidar_sensor);
            serializer.Write(this.collision_trigger_sensor);
            serializer.Write(this.target_trigger_sensor);
        }

        public override string ToString()
        {
            return "AutonomousNavigationExampleAgentStateMsg: " +
            "\npose: " + pose.ToString() +
            "\ntwist: " + twist.ToString() +
            "\ntarget_pose: " + target_pose.ToString() +
            "\nsmart_lidar_sensor: " + smart_lidar_sensor.ToString() +
            "\ncollision_trigger_sensor: " + collision_trigger_sensor.ToString() +
            "\ntarget_trigger_sensor: " + target_trigger_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
