//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class EscoPilotExampleAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/EscoPilotExampleAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.LaserScanMsg laser_scan;
        public Geometry.PoseMsg pose;
        public Geometry.PoseMsg target_pose;
        public TriggerSensorMsg target_trigger_sensor;

        public EscoPilotExampleAgentStateMsg()
        {
            this.laser_scan = new Sensor.LaserScanMsg();
            this.pose = new Geometry.PoseMsg();
            this.target_pose = new Geometry.PoseMsg();
            this.target_trigger_sensor = new TriggerSensorMsg();
        }

        public EscoPilotExampleAgentStateMsg(Sensor.LaserScanMsg laser_scan, Geometry.PoseMsg pose, Geometry.PoseMsg target_pose, TriggerSensorMsg target_trigger_sensor)
        {
            this.laser_scan = laser_scan;
            this.pose = pose;
            this.target_pose = target_pose;
            this.target_trigger_sensor = target_trigger_sensor;
        }

        public static EscoPilotExampleAgentStateMsg Deserialize(MessageDeserializer deserializer) => new EscoPilotExampleAgentStateMsg(deserializer);

        private EscoPilotExampleAgentStateMsg(MessageDeserializer deserializer)
        {
            this.laser_scan = Sensor.LaserScanMsg.Deserialize(deserializer);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.target_trigger_sensor = TriggerSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.laser_scan);
            serializer.Write(this.pose);
            serializer.Write(this.target_pose);
            serializer.Write(this.target_trigger_sensor);
        }

        public override string ToString()
        {
            return "EscoPilotExampleAgentStateMsg: " +
            "\nlaser_scan: " + laser_scan.ToString() +
            "\npose: " + pose.ToString() +
            "\ntarget_pose: " + target_pose.ToString() +
            "\ntarget_trigger_sensor: " + target_trigger_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
