//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class EscoPilotExampleAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/EscoPilotExampleAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg target_velocity;

        public EscoPilotExampleAgentActionMsg()
        {
            this.target_velocity = new Geometry.TwistMsg();
        }

        public EscoPilotExampleAgentActionMsg(Geometry.TwistMsg target_velocity)
        {
            this.target_velocity = target_velocity;
        }

        public static EscoPilotExampleAgentActionMsg Deserialize(MessageDeserializer deserializer) => new EscoPilotExampleAgentActionMsg(deserializer);

        private EscoPilotExampleAgentActionMsg(MessageDeserializer deserializer)
        {
            this.target_velocity = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_velocity);
        }

        public override string ToString()
        {
            return "EscoPilotExampleAgentActionMsg: " +
            "\ntarget_velocity: " + target_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
