//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarTestAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarTestAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public bool lidar_request;

        public LidarTestAgentActionMsg()
        {
            this.lidar_request = false;
        }

        public LidarTestAgentActionMsg(bool lidar_request)
        {
            this.lidar_request = lidar_request;
        }

        public static LidarTestAgentActionMsg Deserialize(MessageDeserializer deserializer) => new LidarTestAgentActionMsg(deserializer);

        private LidarTestAgentActionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.lidar_request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.lidar_request);
        }

        public override string ToString()
        {
            return "LidarTestAgentActionMsg: " +
            "\nlidar_request: " + lidar_request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
