//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarSensorTestAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarSensorTestAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public bool lidar_sensor_request;

        public LidarSensorTestAgentActionMsg()
        {
            this.lidar_sensor_request = false;
        }

        public LidarSensorTestAgentActionMsg(bool lidar_sensor_request)
        {
            this.lidar_sensor_request = lidar_sensor_request;
        }

        public static LidarSensorTestAgentActionMsg Deserialize(MessageDeserializer deserializer) => new LidarSensorTestAgentActionMsg(deserializer);

        private LidarSensorTestAgentActionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.lidar_sensor_request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.lidar_sensor_request);
        }

        public override string ToString()
        {
            return "LidarSensorTestAgentActionMsg: " +
            "\nlidar_sensor_request: " + lidar_sensor_request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
