//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class LidarTestAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/LidarTestAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.LaserScanMsg laser_scan;

        public LidarTestAgentStateMsg()
        {
            this.laser_scan = new Sensor.LaserScanMsg();
        }

        public LidarTestAgentStateMsg(Sensor.LaserScanMsg laser_scan)
        {
            this.laser_scan = laser_scan;
        }

        public static LidarTestAgentStateMsg Deserialize(MessageDeserializer deserializer) => new LidarTestAgentStateMsg(deserializer);

        private LidarTestAgentStateMsg(MessageDeserializer deserializer)
        {
            this.laser_scan = Sensor.LaserScanMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.laser_scan);
        }

        public override string ToString()
        {
            return "LidarTestAgentStateMsg: " +
            "\nlaser_scan: " + laser_scan.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
