//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class PoseSensorAndActuatorTestAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/PoseSensorAndActuatorTestAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;

        public PoseSensorAndActuatorTestAgentStateMsg()
        {
            this.pose = new Geometry.PoseMsg();
        }

        public PoseSensorAndActuatorTestAgentStateMsg(Geometry.PoseMsg pose)
        {
            this.pose = pose;
        }

        public static PoseSensorAndActuatorTestAgentStateMsg Deserialize(MessageDeserializer deserializer) => new PoseSensorAndActuatorTestAgentStateMsg(deserializer);

        private PoseSensorAndActuatorTestAgentStateMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "PoseSensorAndActuatorTestAgentStateMsg: " +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
