//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;
        public Geometry.TwistMsg twist;
        public SmartLidarSensorMsg smart_lidar_sensor;
        public TurretSensorMsg turret_sensor;
        public TriggerSensorMsg collision_trigger_sensor;

        public ShootingExampleAgentStateMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.twist = new Geometry.TwistMsg();
            this.smart_lidar_sensor = new SmartLidarSensorMsg();
            this.turret_sensor = new TurretSensorMsg();
            this.collision_trigger_sensor = new TriggerSensorMsg();
        }

        public ShootingExampleAgentStateMsg(Geometry.PoseMsg pose, Geometry.TwistMsg twist, SmartLidarSensorMsg smart_lidar_sensor, TurretSensorMsg turret_sensor, TriggerSensorMsg collision_trigger_sensor)
        {
            this.pose = pose;
            this.twist = twist;
            this.smart_lidar_sensor = smart_lidar_sensor;
            this.turret_sensor = turret_sensor;
            this.collision_trigger_sensor = collision_trigger_sensor;
        }

        public static ShootingExampleAgentStateMsg Deserialize(MessageDeserializer deserializer) => new ShootingExampleAgentStateMsg(deserializer);

        private ShootingExampleAgentStateMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
            this.smart_lidar_sensor = SmartLidarSensorMsg.Deserialize(deserializer);
            this.turret_sensor = TurretSensorMsg.Deserialize(deserializer);
            this.collision_trigger_sensor = TriggerSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.twist);
            serializer.Write(this.smart_lidar_sensor);
            serializer.Write(this.turret_sensor);
            serializer.Write(this.collision_trigger_sensor);
        }

        public override string ToString()
        {
            return "ShootingExampleAgentStateMsg: " +
            "\npose: " + pose.ToString() +
            "\ntwist: " + twist.ToString() +
            "\nsmart_lidar_sensor: " + smart_lidar_sensor.ToString() +
            "\nturret_sensor: " + turret_sensor.ToString() +
            "\ncollision_trigger_sensor: " + collision_trigger_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
