//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleAgentResetMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleAgentReset";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg agent_target_pose;
        public Geometry.PoseMsg target_target_pose;

        public ShootingExampleAgentResetMsg()
        {
            this.agent_target_pose = new Geometry.PoseMsg();
            this.target_target_pose = new Geometry.PoseMsg();
        }

        public ShootingExampleAgentResetMsg(Geometry.PoseMsg agent_target_pose, Geometry.PoseMsg target_target_pose)
        {
            this.agent_target_pose = agent_target_pose;
            this.target_target_pose = target_target_pose;
        }

        public static ShootingExampleAgentResetMsg Deserialize(MessageDeserializer deserializer) => new ShootingExampleAgentResetMsg(deserializer);

        private ShootingExampleAgentResetMsg(MessageDeserializer deserializer)
        {
            this.agent_target_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.target_target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_target_pose);
            serializer.Write(this.target_target_pose);
        }

        public override string ToString()
        {
            return "ShootingExampleAgentResetMsg: " +
            "\nagent_target_pose: " + agent_target_pose.ToString() +
            "\ntarget_target_pose: " + target_target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
