//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class ShootingExampleAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/ShootingExampleAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg twist;

        public ShootingExampleAgentActionMsg()
        {
            this.twist = new Geometry.TwistMsg();
        }

        public ShootingExampleAgentActionMsg(Geometry.TwistMsg twist)
        {
            this.twist = twist;
        }

        public static ShootingExampleAgentActionMsg Deserialize(MessageDeserializer deserializer) => new ShootingExampleAgentActionMsg(deserializer);

        private ShootingExampleAgentActionMsg(MessageDeserializer deserializer)
        {
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "ShootingExampleAgentActionMsg: " +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
