//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class SmartLaserScan2DMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/SmartLaserScan2D";
        public override string RosMessageName => k_RosMessageName;

        public float angle_min;
        public float angle_max;
        public float angle_increment;
        public float range_min;
        public float range_max;
        public float[] ranges;
        public int[] tags;

        public SmartLaserScan2DMsg()
        {
            this.angle_min = 0.0f;
            this.angle_max = 0.0f;
            this.angle_increment = 0.0f;
            this.range_min = 0.0f;
            this.range_max = 0.0f;
            this.ranges = new float[0];
            this.tags = new int[0];
        }

        public SmartLaserScan2DMsg(float angle_min, float angle_max, float angle_increment, float range_min, float range_max, float[] ranges, int[] tags)
        {
            this.angle_min = angle_min;
            this.angle_max = angle_max;
            this.angle_increment = angle_increment;
            this.range_min = range_min;
            this.range_max = range_max;
            this.ranges = ranges;
            this.tags = tags;
        }

        public static SmartLaserScan2DMsg Deserialize(MessageDeserializer deserializer) => new SmartLaserScan2DMsg(deserializer);

        private SmartLaserScan2DMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angle_min);
            deserializer.Read(out this.angle_max);
            deserializer.Read(out this.angle_increment);
            deserializer.Read(out this.range_min);
            deserializer.Read(out this.range_max);
            deserializer.Read(out this.ranges, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.tags, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angle_min);
            serializer.Write(this.angle_max);
            serializer.Write(this.angle_increment);
            serializer.Write(this.range_min);
            serializer.Write(this.range_max);
            serializer.WriteLength(this.ranges);
            serializer.Write(this.ranges);
            serializer.WriteLength(this.tags);
            serializer.Write(this.tags);
        }

        public override string ToString()
        {
            return "SmartLaserScan2DMsg: " +
            "\nangle_min: " + angle_min.ToString() +
            "\nangle_max: " + angle_max.ToString() +
            "\nangle_increment: " + angle_increment.ToString() +
            "\nrange_min: " + range_min.ToString() +
            "\nrange_max: " + range_max.ToString() +
            "\nranges: " + System.String.Join(", ", ranges.ToList()) +
            "\ntags: " + System.String.Join(", ", tags.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
