//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TankStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TankState";
        public override string RosMessageName => k_RosMessageName;

        public Pose2DMsg pose2d;
        public Twist2DMsg twist2d;
        public HealthInfoMsg health_info;
        public SmartLaserScan2DMsg smart_laser_scan2d;
        public Turret2DSensorMsg turret2d_sensor;

        public TankStateMsg()
        {
            this.pose2d = new Pose2DMsg();
            this.twist2d = new Twist2DMsg();
            this.health_info = new HealthInfoMsg();
            this.smart_laser_scan2d = new SmartLaserScan2DMsg();
            this.turret2d_sensor = new Turret2DSensorMsg();
        }

        public TankStateMsg(Pose2DMsg pose2d, Twist2DMsg twist2d, HealthInfoMsg health_info, SmartLaserScan2DMsg smart_laser_scan2d, Turret2DSensorMsg turret2d_sensor)
        {
            this.pose2d = pose2d;
            this.twist2d = twist2d;
            this.health_info = health_info;
            this.smart_laser_scan2d = smart_laser_scan2d;
            this.turret2d_sensor = turret2d_sensor;
        }

        public static TankStateMsg Deserialize(MessageDeserializer deserializer) => new TankStateMsg(deserializer);

        private TankStateMsg(MessageDeserializer deserializer)
        {
            this.pose2d = Pose2DMsg.Deserialize(deserializer);
            this.twist2d = Twist2DMsg.Deserialize(deserializer);
            this.health_info = HealthInfoMsg.Deserialize(deserializer);
            this.smart_laser_scan2d = SmartLaserScan2DMsg.Deserialize(deserializer);
            this.turret2d_sensor = Turret2DSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose2d);
            serializer.Write(this.twist2d);
            serializer.Write(this.health_info);
            serializer.Write(this.smart_laser_scan2d);
            serializer.Write(this.turret2d_sensor);
        }

        public override string ToString()
        {
            return "TankStateMsg: " +
            "\npose2d: " + pose2d.ToString() +
            "\ntwist2d: " + twist2d.ToString() +
            "\nhealth_info: " + health_info.ToString() +
            "\nsmart_laser_scan2d: " + smart_laser_scan2d.ToString() +
            "\nturret2d_sensor: " + turret2d_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
