//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TankActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TankAction";
        public override string RosMessageName => k_RosMessageName;

        public Twist2DMsg target_twist2d;
        public Turret2DActuatorMsg turret2d_actuator;

        public TankActionMsg()
        {
            this.target_twist2d = new Twist2DMsg();
            this.turret2d_actuator = new Turret2DActuatorMsg();
        }

        public TankActionMsg(Twist2DMsg target_twist2d, Turret2DActuatorMsg turret2d_actuator)
        {
            this.target_twist2d = target_twist2d;
            this.turret2d_actuator = turret2d_actuator;
        }

        public static TankActionMsg Deserialize(MessageDeserializer deserializer) => new TankActionMsg(deserializer);

        private TankActionMsg(MessageDeserializer deserializer)
        {
            this.target_twist2d = Twist2DMsg.Deserialize(deserializer);
            this.turret2d_actuator = Turret2DActuatorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_twist2d);
            serializer.Write(this.turret2d_actuator);
        }

        public override string ToString()
        {
            return "TankActionMsg: " +
            "\ntarget_twist2d: " + target_twist2d.ToString() +
            "\nturret2d_actuator: " + turret2d_actuator.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
