//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TriggerSensorTestAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TriggerSensorTestAgentState";
        public override string RosMessageName => k_RosMessageName;

        public TriggerSensorMsg trigger_sensor_01_data;
        public TriggerSensorMsg trigger_sensor_02_data;
        public TriggerSensorMsg trigger_sensor_03_data;
        public TriggerSensorMsg trigger_sensor_04_data;

        public TriggerSensorTestAgentStateMsg()
        {
            this.trigger_sensor_01_data = new TriggerSensorMsg();
            this.trigger_sensor_02_data = new TriggerSensorMsg();
            this.trigger_sensor_03_data = new TriggerSensorMsg();
            this.trigger_sensor_04_data = new TriggerSensorMsg();
        }

        public TriggerSensorTestAgentStateMsg(TriggerSensorMsg trigger_sensor_01_data, TriggerSensorMsg trigger_sensor_02_data, TriggerSensorMsg trigger_sensor_03_data, TriggerSensorMsg trigger_sensor_04_data)
        {
            this.trigger_sensor_01_data = trigger_sensor_01_data;
            this.trigger_sensor_02_data = trigger_sensor_02_data;
            this.trigger_sensor_03_data = trigger_sensor_03_data;
            this.trigger_sensor_04_data = trigger_sensor_04_data;
        }

        public static TriggerSensorTestAgentStateMsg Deserialize(MessageDeserializer deserializer) => new TriggerSensorTestAgentStateMsg(deserializer);

        private TriggerSensorTestAgentStateMsg(MessageDeserializer deserializer)
        {
            this.trigger_sensor_01_data = TriggerSensorMsg.Deserialize(deserializer);
            this.trigger_sensor_02_data = TriggerSensorMsg.Deserialize(deserializer);
            this.trigger_sensor_03_data = TriggerSensorMsg.Deserialize(deserializer);
            this.trigger_sensor_04_data = TriggerSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trigger_sensor_01_data);
            serializer.Write(this.trigger_sensor_02_data);
            serializer.Write(this.trigger_sensor_03_data);
            serializer.Write(this.trigger_sensor_04_data);
        }

        public override string ToString()
        {
            return "TriggerSensorTestAgentStateMsg: " +
            "\ntrigger_sensor_01_data: " + trigger_sensor_01_data.ToString() +
            "\ntrigger_sensor_02_data: " + trigger_sensor_02_data.ToString() +
            "\ntrigger_sensor_03_data: " + trigger_sensor_03_data.ToString() +
            "\ntrigger_sensor_04_data: " + trigger_sensor_04_data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
