//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TriggerSensorTestAgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TriggerSensorTestAgentAction";
        public override string RosMessageName => k_RosMessageName;

        public bool trigger_sensor_request;

        public TriggerSensorTestAgentActionMsg()
        {
            this.trigger_sensor_request = false;
        }

        public TriggerSensorTestAgentActionMsg(bool trigger_sensor_request)
        {
            this.trigger_sensor_request = trigger_sensor_request;
        }

        public static TriggerSensorTestAgentActionMsg Deserialize(MessageDeserializer deserializer) => new TriggerSensorTestAgentActionMsg(deserializer);

        private TriggerSensorTestAgentActionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trigger_sensor_request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trigger_sensor_request);
        }

        public override string ToString()
        {
            return "TriggerSensorTestAgentActionMsg: " +
            "\ntrigger_sensor_request: " + trigger_sensor_request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
