//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TurretSensorMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TurretSensor";
        public override string RosMessageName => k_RosMessageName;

        public float current_angle;
        public bool hit;

        public TurretSensorMsg()
        {
            this.current_angle = 0.0f;
            this.hit = false;
        }

        public TurretSensorMsg(float current_angle, bool hit)
        {
            this.current_angle = current_angle;
            this.hit = hit;
        }

        public static TurretSensorMsg Deserialize(MessageDeserializer deserializer) => new TurretSensorMsg(deserializer);

        private TurretSensorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_angle);
            deserializer.Read(out this.hit);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_angle);
            serializer.Write(this.hit);
        }

        public override string ToString()
        {
            return "TurretSensorMsg: " +
            "\ncurrent_angle: " + current_angle.ToString() +
            "\nhit: " + hit.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
