//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TurretActuatorMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TurretActuator";
        public override string RosMessageName => k_RosMessageName;

        public float target_angle;
        public bool fire;

        public TurretActuatorMsg()
        {
            this.target_angle = 0.0f;
            this.fire = false;
        }

        public TurretActuatorMsg(float target_angle, bool fire)
        {
            this.target_angle = target_angle;
            this.fire = fire;
        }

        public static TurretActuatorMsg Deserialize(MessageDeserializer deserializer) => new TurretActuatorMsg(deserializer);

        private TurretActuatorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target_angle);
            deserializer.Read(out this.fire);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_angle);
            serializer.Write(this.fire);
        }

        public override string ToString()
        {
            return "TurretActuatorMsg: " +
            "\ntarget_angle: " + target_angle.ToString() +
            "\nfire: " + fire.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
