//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TwistSensorAndActuatorTestAgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TwistSensorAndActuatorTestAgentState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg twist;

        public TwistSensorAndActuatorTestAgentStateMsg()
        {
            this.twist = new Geometry.TwistMsg();
        }

        public TwistSensorAndActuatorTestAgentStateMsg(Geometry.TwistMsg twist)
        {
            this.twist = twist;
        }

        public static TwistSensorAndActuatorTestAgentStateMsg Deserialize(MessageDeserializer deserializer) => new TwistSensorAndActuatorTestAgentStateMsg(deserializer);

        private TwistSensorAndActuatorTestAgentStateMsg(MessageDeserializer deserializer)
        {
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "TwistSensorAndActuatorTestAgentStateMsg: " +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
