//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC1AgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC1AgentState";
        public override string RosMessageName => k_RosMessageName;

        public TankStateMsg tank_state;
        public Pose2DMsg target_pose2d;
        public TriggerSensorMsg target_trigger_sensor;

        public UC1AgentStateMsg()
        {
            this.tank_state = new TankStateMsg();
            this.target_pose2d = new Pose2DMsg();
            this.target_trigger_sensor = new TriggerSensorMsg();
        }

        public UC1AgentStateMsg(TankStateMsg tank_state, Pose2DMsg target_pose2d, TriggerSensorMsg target_trigger_sensor)
        {
            this.tank_state = tank_state;
            this.target_pose2d = target_pose2d;
            this.target_trigger_sensor = target_trigger_sensor;
        }

        public static UC1AgentStateMsg Deserialize(MessageDeserializer deserializer) => new UC1AgentStateMsg(deserializer);

        private UC1AgentStateMsg(MessageDeserializer deserializer)
        {
            this.tank_state = TankStateMsg.Deserialize(deserializer);
            this.target_pose2d = Pose2DMsg.Deserialize(deserializer);
            this.target_trigger_sensor = TriggerSensorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank_state);
            serializer.Write(this.target_pose2d);
            serializer.Write(this.target_trigger_sensor);
        }

        public override string ToString()
        {
            return "UC1AgentStateMsg: " +
            "\ntank_state: " + tank_state.ToString() +
            "\ntarget_pose2d: " + target_pose2d.ToString() +
            "\ntarget_trigger_sensor: " + target_trigger_sensor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
