//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC2AgentActionMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC2AgentAction";
        public override string RosMessageName => k_RosMessageName;

        public TankActionMsg tank_action;

        public UC2AgentActionMsg()
        {
            this.tank_action = new TankActionMsg();
        }

        public UC2AgentActionMsg(TankActionMsg tank_action)
        {
            this.tank_action = tank_action;
        }

        public static UC2AgentActionMsg Deserialize(MessageDeserializer deserializer) => new UC2AgentActionMsg(deserializer);

        private UC2AgentActionMsg(MessageDeserializer deserializer)
        {
            this.tank_action = TankActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank_action);
        }

        public override string ToString()
        {
            return "UC2AgentActionMsg: " +
            "\ntank_action: " + tank_action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
