//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC2AgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC2AgentState";
        public override string RosMessageName => k_RosMessageName;

        public TankStateMsg tank_state;
        public Pose2DMsg target_pose2d;
        public HealthInfoMsg target_health_info;

        public UC2AgentStateMsg()
        {
            this.tank_state = new TankStateMsg();
            this.target_pose2d = new Pose2DMsg();
            this.target_health_info = new HealthInfoMsg();
        }

        public UC2AgentStateMsg(TankStateMsg tank_state, Pose2DMsg target_pose2d, HealthInfoMsg target_health_info)
        {
            this.tank_state = tank_state;
            this.target_pose2d = target_pose2d;
            this.target_health_info = target_health_info;
        }

        public static UC2AgentStateMsg Deserialize(MessageDeserializer deserializer) => new UC2AgentStateMsg(deserializer);

        private UC2AgentStateMsg(MessageDeserializer deserializer)
        {
            this.tank_state = TankStateMsg.Deserialize(deserializer);
            this.target_pose2d = Pose2DMsg.Deserialize(deserializer);
            this.target_health_info = HealthInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank_state);
            serializer.Write(this.target_pose2d);
            serializer.Write(this.target_health_info);
        }

        public override string ToString()
        {
            return "UC2AgentStateMsg: " +
            "\ntank_state: " + tank_state.ToString() +
            "\ntarget_pose2d: " + target_pose2d.ToString() +
            "\ntarget_health_info: " + target_health_info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
