environment:
  id: 'uc2'
  n_environments: 16
  # seed: 0

  unity:
    headless_mode: false
    pause: true
    sample_time: 0.1
    fixed_delta_time: 0.01
    fixed_updates_per_step: 2

  render:
    render_mode: 'rgb_array'
    use_video_wrapper: false
    video_trigger: 5000
    video_length: 500


training:
  experiment_name: 'ppo'
  algorithm: 'PPO'

  pretrained_model:
    use_pretrained_model: false
    experiment_name: null
    checkpoint: null

  total_timesteps: 7000000

  logging:
    verbose: 2
    n_checkpoints: 10
    use_wandb: true
    wandb_entity: 'rl-gods'
    
  evaluation:
    eval_freq: 10000
    eval_episodes: 32
    # seed: 5
    # num_episodes: 5
    # num_evals: 15


deployment:
  experiment_name: 'ppo_2024-10-05_09-24-04'
  checkpoint: 'best_model'
