environment:
  id: 'uc2'
  n_environments: 8
  # seed: 0

  unity:
    headless_mode: false
    pause: true
    sample_time: 0.1
    fixed_delta_time: 0.01
    fixed_updates_per_step: 2

  render:
    render_mode: 'rgb_array'
    use_video_wrapper: false
    video_trigger: 5000
    video_length: 500


training:
  experiment_name: 'test'
  algorithm: 'PPO'

  pretrained_model:
    use_pretrained_model: false
    experiment_name: null
    checkpoint: null

  total_timesteps: 500000

  logging:
    verbose: 2
    log_freq: 1000
    progress_bar: true
    use_wandb: true
    wandb_entity: 'rl-gods'
    
  evaluation:
    # seed: 5
    # num_episodes: 5
    # num_evals: 15


deployment:
  algorithm: 'PPO'
  experiment_name: 'test_2024-09-29_21-59-48'
  checkpoint: 'model'
